- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
     cloud: openstack
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke
  - name: Check the instances status 
    wait_for:
      host: "{{ item.public_v4 }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: localhost
    with_items:
      - "{{ openstack_info.openstack_servers }}"
    when: "'winrm' not in ansible_connection"
    tags:
     - "Check system up status"



  - name: Curl website
    uri:
     url: "http://{{item.public_v4}}"
     return_content: yes
    with_items:
      - "{{ openstack_info.openstack_servers }}"
    register: webpage
    tags:
      - osp.smoke

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - osp.smoke
